version: "3.5"

services:
  angular-pw:
    ports:
      - 4300:4200
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: "angular-pw"
    volumes:
      - ./:/usr/src/app/
#      - ../config:/usr/src/app/config
#      - ../mock:/usr/src/app/mock

networks:
  default:
    external:
      name: docker_registration-django-net
